### ISSUE TITLE
Cursor doesn't rotate properly if object is rotated as a child of an entity

### ISSUE THREAD

**Issue by casonclagg** [jujunjun110/aframe-crawling-cursor#5]
<a-entity>
       
	<a-sphere radius="0.35" rotation="0 -90 0"></a-sphere>
</a-entity>

The cursor needs to have a global view of where objects are and what direction they are facing.

<img width="943" alt="screen shot 2017-01-24 at 12 42 32 am" src="https://cloud.githubusercontent.com/assets/20270700/22236888/0fd8a8f4-e1ce-11e6-9809-83d91b6fec3b.png">

**Comment by jujunjun110** [comment]
Thanks for information.
I will fix when I have time 😉

**Comment by casonclagg** [comment]
Related: https://github.com/mrdoob/three.js/issues/2368

I'm trying to fix it, but not having much luck.

This is where I am at, maybe you have some insight as to why this doesn't work: 

            var lookAtTarget = new THREE.Vector3().addVectors(intersection.point, intersection.face.normal);
            var rotationMatrix = new THREE.Matrix4();
            let rot = intersection.object.getWorldRotation()
            rotationMatrix.makeRotationFromEuler(new THREE.Euler(rot, 'XYZ'));
            lookAtTarget.applyMatrix4(rotationMatrix)
            data.target.object3D.lookAt(lookAtTarget);

My rotationMatrix has NaN's in it, so that's obviously not good... =(

**Comment by jujunjun110** [comment]
I had a luck to fix this issue like this😎

```javascript
var global_normal = intersection.face.normal.clone();

// a matrix which represents item's movement, rotation and scale on global world
var mat = intersection.object.matrixWorld;

// remove parallel movement from the matrix
mat.setPosition(new THREE.Vector3(0, 0, 0));

// change local normal into global normal
global_normal.applyMatrix4(mat).normalize();

// look at target coordinate = intersection coordinate + global normal vector
var lookAtTarget = new THREE.Vector3().addVectors(intersection.point, global_normal);
data.target.object3D.lookAt(lookAtTarget);

// cursor coordinate = intersection coordinate + normal vector * 0.05(hover 5cm above intersection point)
var cursorPosition = new THREE.Vector3().addVectors(intersection.point, intersection.face.normal.multiplyScalar(0.05));
data.target.setAttribute("position", cursorPosition);
```
